---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
## 網站資料爬取
```{r}
library(rvest)

pttResult<-NULL
for(n in 1:6){
indexno = 5300-n
url<-paste0("https://www.ptt.cc/bbs/movie/index",indexno,".html")
pttContent<-read_html(url)
post_title <- pttContent %>% html_nodes(".title") %>% html_text()
post_pushNum<- pttContent %>% html_nodes(".nrec") %>% html_text()
post_author<- pttContent %>% html_nodes(".author") %>% html_text()
pttMovie<-data.frame(title=post_title,pushNum=post_pushNum,author=post_author)
pttResult<-rbind(pttResult,pttMovie)
}
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(pttResult)
```

## 解釋爬蟲結果 
```{r}
str(pttResult[1])
```

執行str(pttResult[1])，pttResult[1]用來取pttResult的第一個欄位，也就是標題
結果為:'data.frame':118 obs. of  1 variable，代表這次執行結果總共有118篇文章
(根據時間不同，文章數量可能會變動)

```{r}
maxPost<-max(table(pttResult$author,exclude="-"))
for(m in 1:(length(table(pttResult$author)))){
  if(((table(pttResult$author))[[m]])==maxPost)
    print((table(pttResult$author))[m])
}
```

先用table找出每個作者的貼文總數，再用max取最大值("-"代表已刪除貼文，要排除在外)
再用迴圈找貼文數和maxPost一樣的作者，並print出名字和貼文數，結果為jay5566，總共6篇貼文
(根據時間不同，結果可能會不同)

經過這次的爬蟲結果得出以下結論:

1.最近的新片攻殼機動隊和國片目擊者討論度很高
2."贈票"的文章推文數都很多
3.大部分都是討論好萊塢片，其他地區的電影討論度不高
